fix(deps): bump bootstrap image for release-0.59 vgpu lane (#4717)
This brings a podman update which is required to fix the following error
with newer kernels.

    Error: OCI runtime error: crun: chmod `run/shm`: Operation not supported

See https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-kind-1.23-vgpu-0.59

Signed-off-by: Denis Ollier <dollierp@redhat.com>