hco,presubmit: Update golang bootstrap image (#2532)
This image uses podman
The old image has problems suddenly with docker
Error: statfs /var/run/docker.sock: no such file or directory
We need to use podman anyhow.

Signed-off-by: Or Shoval <oshoval@redhat.com>

Signed-off-by: Or Shoval <oshoval@redhat.com>