prow, referee, monitoring: add ServiceMonitor CRD
testing env doesn't have the ServiceMonitor CRD, so deployment of the
ServiceMonitor fails:

```
error: resource mapping not found for name: "referee" namespace: "" from "STDIN": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first
```

https: //prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3438/pull-project-infra-prow-deploy-test/1795471758619316224#1:build-log.txt%3A592
Signed-off-by: Daniel Hiller <dhiller@redhat.com>